import { strFromU8, unzipSync } from 'fflate'

export type CellValue = string | number
/** Sheet name → ('B24' → value). */
export type Workbook = Map<string, Map<string, CellValue>>

// A minimal reader: it reads the XML with regular expressions instead of a real parser. That is
// fine for the single workbook generated by Excel that this import targets (well-formed, no CDATA,
// no namespace prefixes on the spreadsheet elements); it is not a general-purpose .xlsx reader.

const ENTITIES: Record<string, string> = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'" }

// One pass, so a decoded "&" is never decoded again ("&amp;lt;" must end up as "&lt;").
function decodeEntities(text: string): string {
  return text.replace(/&(?:#x([0-9a-fA-F]+)|#(\d+)|(amp|lt|gt|quot|apos));/g, (_m, hex, dec, name) =>
    name ? ENTITIES[name]! : String.fromCodePoint(hex ? parseInt(hex, 16) : parseInt(dec, 10)),
  )
}

function attributes(tag: string): Record<string, string> {
  const result: Record<string, string> = {}
  for (const match of tag.matchAll(/([\w:.-]+)\s*=\s*"([^"]*)"/g)) {
    result[match[1]!] = decodeEntities(match[2]!)
  }
  return result
}

// Concatenates every <t> of a string item: a rich-text item splits its text into several <r> runs.
// Phonetic runs (<rPh>) are not part of the visible text.
function textOf(xml: string): string {
  const visible = xml.replace(/<rPh\b[\s\S]*?<\/rPh>/g, '')
  let text = ''
  for (const match of visible.matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)) text += match[1]
  return decodeEntities(text)
}

function readSharedStrings(xml: string | undefined): string[] {
  if (!xml) return []
  const strings: string[] = []
  for (const match of xml.matchAll(/<si\s*\/>|<si(?:\s[^>]*)?>([\s\S]*?)<\/si>/g)) {
    strings.push(match[1] === undefined ? '' : textOf(match[1]))
  }
  return strings
}

function readSheet(xml: string, sharedStrings: string[]): Map<string, CellValue> {
  const cells = new Map<string, CellValue>()
  for (const match of xml.matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)) {
    const { r: ref, t: type } = attributes(match[1]!)
    const body = match[2]
    if (!ref || body === undefined) continue
    if (type === 'e') continue // error values such as #VALUE! carry no data
    if (type === 'inlineStr') {
      cells.set(ref, textOf(body))
      continue
    }
    const raw = /<v>([\s\S]*?)<\/v>/.exec(body)?.[1]
    if (raw === undefined) continue
    if (type === 's') {
      const text = sharedStrings[Number(raw)]
      if (text !== undefined) cells.set(ref, text)
    } else if (type === 'str') {
      cells.set(ref, decodeEntities(raw))
    } else {
      const value = Number(raw)
      if (raw.trim() !== '' && Number.isFinite(value)) cells.set(ref, value)
    }
  }
  return cells
}

export function readXlsx(bytes: Uint8Array): Workbook {
  const files = unzipSync(bytes)
  const read = (path: string): string | undefined => {
    const file = files[path]
    return file ? strFromU8(file) : undefined
  }

  const workbookXml = read('xl/workbook.xml')
  const relsXml = read('xl/_rels/workbook.xml.rels')
  if (workbookXml === undefined || relsXml === undefined) {
    throw new Error('El archivo no parece un .xlsx válido (falta xl/workbook.xml).')
  }

  const targets = new Map<string, string>()
  for (const match of relsXml.matchAll(/<Relationship\b[^>]*>/g)) {
    const { Id, Target } = attributes(match[0])
    if (Id && Target) targets.set(Id, Target)
  }

  const sharedStrings = readSharedStrings(read('xl/sharedStrings.xml'))
  const workbook: Workbook = new Map()
  for (const match of workbookXml.matchAll(/<sheet\b[^>]*>/g)) {
    const { name, 'r:id': id } = attributes(match[0])
    const target = id ? targets.get(id) : undefined
    if (!name || !target) continue
    // A target is relative to xl/ unless it starts with a slash.
    const path = target.startsWith('/') ? target.slice(1) : `xl/${target}`
    const sheetXml = read(path)
    if (sheetXml === undefined) throw new Error(`Falta la hoja "${name}" (${path}) en el archivo.`)
    workbook.set(name, readSheet(sheetXml, sharedStrings))
  }
  return workbook
}
